/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.Usuario;

import ClienteDto.ClienteDto;
import Control.ControlCliente;
import Dominio.Clientes;
import Dominio.Cuentas;
import Excepciones.PersistenciaExcepcion;
import interfaz.inicio.Inicio;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class InicioUsuario extends javax.swing.JFrame {

    private final Clientes cli;
    private final ControlCliente control;

    /**
     * Creates new form InicioUsuario
     *
     * @param control
     * @param cliente
     */
    public InicioUsuario(ControlCliente control, Clientes cliente) {
        initComponents();
        this.control = control;
        this.cli = cliente;
        this.txtNomUsu.setText(cliente.getNombre());
        
        this.llenarTabla(cli.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomUsu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCuentas = new javax.swing.JTable();
        transeferencia = new javax.swing.JButton();
        retiroSinTarjeta = new javax.swing.JButton();
        historial = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        AgregarCuenta = new javax.swing.JButton();
        EliminarCuenta = new javax.swing.JButton();
        Deposito = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(10, 80, 186));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/jesus/Documentos/GitHub/Proyecto1_BDA/Banco/Banco/BancoInterfaz/src/main/resource/usuario32.png")); // NOI18N

        txtNomUsu.setEditable(false);
        txtNomUsu.setBackground(new java.awt.Color(10, 80, 186));
        txtNomUsu.setFont(new java.awt.Font("TeX Gyre Adventor", 0, 18)); // NOI18N
        txtNomUsu.setForeground(new java.awt.Color(255, 255, 255));
        txtNomUsu.setBorder(null);

        jLabel3.setFont(new java.awt.Font("TeX Gyre Adventor", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido,");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("TeX Gyre Adventor", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 80, 186));
        jLabel4.setText("Cuentas");

        jtCuentas.setAutoCreateRowSorter(true);
        jtCuentas.setBackground(new java.awt.Color(204, 204, 204));
        jtCuentas.setFont(new java.awt.Font("TeX Gyre Adventor", 0, 12)); // NOI18N
        jtCuentas.setForeground(new java.awt.Color(255, 255, 255));
        jtCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Num de Cuenta", "Saldo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCuentas.setGridColor(new java.awt.Color(0, 0, 0));
        jtCuentas.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jtCuentas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jtCuentas);

        transeferencia.setBackground(new java.awt.Color(10, 80, 186));
        transeferencia.setForeground(new java.awt.Color(255, 255, 255));
        transeferencia.setText("Transeferencia");
        transeferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transeferenciaActionPerformed(evt);
            }
        });

        retiroSinTarjeta.setBackground(new java.awt.Color(10, 80, 186));
        retiroSinTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        retiroSinTarjeta.setText("Retiro sin tarjeta");

        historial.setBackground(new java.awt.Color(10, 80, 186));
        historial.setForeground(new java.awt.Color(255, 255, 255));
        historial.setText("Historial");

        Editar.setBackground(new java.awt.Color(255, 255, 255));
        Editar.setForeground(new java.awt.Color(10, 80, 186));
        Editar.setText("Editar perfil");
        Editar.setBorder(null);
        Editar.setBorderPainted(false);
        Editar.setContentAreaFilled(false);

        AgregarCuenta.setBackground(new java.awt.Color(10, 80, 186));
        AgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCuenta.setText("Agregar cuenta");

        EliminarCuenta.setBackground(new java.awt.Color(10, 80, 186));
        EliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCuenta.setText("Eliminar cuenta");

        Deposito.setBackground(new java.awt.Color(10, 80, 186));
        Deposito.setForeground(new java.awt.Color(255, 255, 255));
        Deposito.setText("Deposito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarCuenta)
                                    .addComponent(EliminarCuenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(retiroSinTarjeta)
                                    .addComponent(Deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transeferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305)
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retiroSinTarjeta)
                    .addComponent(AgregarCuenta)
                    .addComponent(transeferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historial)
                    .addComponent(EliminarCuenta)
                    .addComponent(Deposito))
                .addGap(29, 29, 29))
        );

        cerrarSesion.setBackground(new java.awt.Color(10, 80, 186));
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.setBorder(null);
        cerrarSesion.setBorderPainted(false);
        cerrarSesion.setContentAreaFilled(false);
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSesion)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomUsu)
                        .addComponent(cerrarSesion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void transeferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transeferenciaActionPerformed
        transferencia trans = new transferencia(control, cli);
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transeferenciaActionPerformed

    
    public void llenarTabla(int id) {
        try {
            List<Cuentas> listaHist = control.ConsultarCuentasInicio(id);
            
            DefaultTableModel modeloTabla = (DefaultTableModel) this.jtCuentas.getModel();
            
            modeloTabla.setRowCount(0);
            
            listaHist.forEach(Cuentas -> {
                Object[] filas = new Object[3];
                filas[0] = Cuentas.getNumeroDeCuenta();
                filas[1] = Cuentas.getSaldo();
                filas[2] = Cuentas.getFechaApertura();
                modeloTabla.addRow(filas);
            });
        } catch (PersistenciaExcepcion ex) {
            Logger.getLogger(InicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCuenta;
    private javax.swing.JButton Deposito;
    private javax.swing.JButton Editar;
    private javax.swing.JButton EliminarCuenta;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCuentas;
    private javax.swing.JButton retiroSinTarjeta;
    private javax.swing.JButton transeferencia;
    private javax.swing.JTextField txtNomUsu;
    // End of variables declaration//GEN-END:variables
}
